public class Catch2 {
    public static void main(String [] args)
    {
        try{
            Broken broke = new Broken();

            System.out.println("Testing");

            // Modify the code to catch the exceptions generated by Broken.cracked().
            broke.cracked();
        }
        catch(ArrayIndexOutOfBoundsException e){
            System.out.println("ArrayIndexOutOfBoundsException");
            System.out.println("Finally!");
        }
        catch(NullPointerException e){
            System.out.println("NullPointerException");
            System.out.println("Finally!");
        }
        catch(ArithmeticException e){
            System.out.println("ArithmeticException");
            System.out.println("Finally!");
        }
    }
}

class Broken
{
    // method generates an exception
    public void cracked()
    {
        //ArrayIndexOutOfBoundsException
        // int[] array = {1, 2};
        // for(int i = 0; i <= array.length; i++){
        //     System.out.println(array[i]);
        // }

        //NullPointerException
        // Object obj = null;
        // obj.hashCode();

        //ArithmeticException
        //int i = 0 / 0;
    }
}